### ISSUE TITLE
QFAPI FAPI error

### ISSUE THREAD

**Issue by sargeow** [TheWinABagel/FakerLib#2]
hey i notice that faker doesnt seem to load properly when using QFAPI instead of FAPI. thanks

[crash-2024-06-03_09.44.02.5854-quilt_loader.txt](https://github.com/user-attachments/files/15534687/crash-2024-06-03_09.44.02.5854-quilt_loader.txt)

**Comment by TheWinABagel** [comment]
This looks like it was cause QFAPI was out of date, should be fine now
